# Generated by Django 3.2.9 on 2021-11-20 07:32

# Django
import django.db.models.deletion
from django.conf import settings
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='cena produktu'),
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50, verbose_name='numer')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='data utowrzenia')),
                ('payment_date', models.DateField(verbose_name='data płatności')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shops.order')),
            ],
        ),
    ]
