# Generated by Django 3.2.9 on 2021-11-20 09:33

# Django
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0002_auto_20211120_0732'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name': 'adres', 'verbose_name_plural': 'adresy'},
        ),
    ]
