# Generated by Django 3.2.9 on 2021-11-20 10:02

# Django
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0003_alter_address_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='name',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='nazwa'),
        ),
    ]
